### ISSUE TITLE
EpiStats removed from CRAN as errors not corrected in time

### ISSUE THREAD

**Issue by AmyMikhail** [Epiconcept-Paris/EpiStats#2]
It seems that EpiStats was removed from CRAN because errors occuring with the latest R version (4.3.1) were not corrected in time before release, see [here](https://cran.r-project.org/web/packages/EpiStats/index.html).

The error appears to be here:

```
 > CCInter(DF, "ill", "wmousse", by = "tira")
    Warning in cbind(c1, c2, c3, c4) :
     number of rows of result is not a multiple of vector length (arg 1)
    Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length
    Calls: CCInter ... row.names<- -> row.names<-.data.frame -> .rowNamesDF<-
    Execution halted
```

Is this package orphaned and if so would it be possible for someone else at EpiConcept to take it on?  Alternately if the package is no longer supported could you recommend an alternative for the `CCInter()` function in a currently supported package?

**Comment by loremerdrignac** [comment]
Dear @AmyMikhail 
Thank you for your message and apologies for coming back to you after such a delay.
We are currently working on a new CRAN submission and hope to come back to you soon with some good news.
Until then, you can find a functional version of the package on the branch [release_1.4-1_2020-04-21](https://github.com/Epiconcept-Paris/EpiStats/tree/release_1.4-1_2020-04-21).
Please do not hesitate to let us know if you spot any issue with this latest version!
Best wishes,
Lore

**Comment by AmyMikhail** [comment]
@loremerdrignac many thanks, that seems to have worked.  In case anyone is using pacman it can be installed and loaded with:

```
pacman::p_load_gh(
  "Epiconcept-Paris/EpiStats@release_1.4-1_2020-04-21"
  )
```

**Comment by loremerdrignac** [comment]
Wonderful, thank you so much @AmyMikhail for testing it on your side so promptly!
In that case, we will start asap the process of submitting it to the CRAN and will keep you posted.
Best wishes,
Lore

**Comment by loremerdrignac** [comment]
Dear @AmyMikhail,
Please note that EpiStats is back on the CRAN again: [EpiStats](https://cran.r-project.org/package=EpiStats)!
Additionally, the work in progress branch (release_1.4-1_2020-04-21) has been merged into the main branch and deleted. Therefore, please install the EpiStats package either from the CRAN `install.packages(EpiStats)` or from the main branch of EpiStats GitHub repo `devtools::install_github("Epiconcept-Paris/EpiStats")`.
Sorry for the inconvenience!
Best wishes,
Lore
