### ISSUE TITLE
CCInter / CSInter: Error if there is 0 in one of the 2by2 tables

### ISSUE THREAD

**Issue by Estherki** [Epiconcept-Paris/EpiStats#5]
Hi Epiconcept team :)
When using the function ccinter in EpiStats, if there is a 0 in my 2 by 2 table, I get the error message as pasted below. I imagine it is because the logistic regression cannot run with a zero in the cell. Could you kindly create a more informative error message?
All the best,
Esther
![image](https://github.com/Epiconcept-Paris/EpiStats/assets/3163173/bf4c655f-703f-4851-a389-a8c8c6487bde)

**Comment by loremerdrignac** [comment]
Hi @Estherki 
Thank you for your feedback!
I cannot reproduce this excat error message. Could I kindly ask you to provide me with a test dataset?
Thank you!
