### ISSUE TITLE
cctable and cc will not run if one variable listed includes only 1s or only 0s

### ISSUE THREAD

**Issue by epi-jhd** [Epiconcept-Paris/EpiStats#6]
If a one of the variables that wish to test with cctable contains only 1 or only 0, then the function returns an error.

![image](https://github.com/Epiconcept-Paris/EpiStats/assets/97244621/a519c774-ab24-4735-9529-f9b3220aa7a7)

A similar error appears in cc()
![image](https://github.com/Epiconcept-Paris/EpiStats/assets/97244621/05addae4-556f-47d8-8556-0d39ae785214)

**Comment by loremerdrignac** [comment]
This should be fixed in the branch [bugfix_postrelease](https://github.com/Epiconcept-Paris/EpiStats/tree/bugfix_postrelease)
