### ISSUE TITLE
cc does not recognise variable names when inserted in the form of an object

### ISSUE THREAD

**Issue by epi-jhd** [Epiconcept-Paris/EpiStats#7]
cc only recognises variable names if input in character format. 
If assign the variable to an object, or assign it in a for loop then the function cannot identify the variable and returns an error.
![image](https://github.com/Epiconcept-Paris/EpiStats/assets/97244621/47e1d5c9-2bee-4bb1-9cf0-b9ad13a38725)

**Comment by loremerdrignac** [comment]
This should be fixed in the branch [bugfix_postrelease](https://github.com/Epiconcept-Paris/EpiStats/tree/bugfix_postrelease)
